module.exports =
{
	"get_templates_list"		: {
									"@acl"  : [$ACL.USER_TYPE_ADMIN, $ACL.USER_TYPE_OFFICER],
									"@doc"  : "Get paginated list of report templates. Officers see only active templates for their communities.",
									"#token": "s",
									"community_id"   : "o:i:0***Filter by community ID (0 = all)",
									"status"         : "o:s:***Filter by status: " + $DataItems.getListForApiDoc("report_template_status"),
									"category"       : "o:s:***Filter by category: " + $DataItems.getListForApiDoc("report_category"),
									"search_text"    : "o:s:***Free-text search across template name",
									"sort_by"        : "o:s:name***Sort column: name, category, status, last_modified",
									"sort_dir"       : "o:s:asc***Sort direction: asc or desc",
									"page"           : "o:i:0***Page number (0-based)",
								},
	"get_template"				: {
									"@acl"  : [$ACL.USER_TYPE_ADMIN, $ACL.USER_TYPE_OFFICER],
									"@doc"  : "Get template details with sections and fields. Officers can only access active templates for their communities.",
									"#token": "s",
									"template_id"    : "i***Report Template ID",
								},
	"create_template"			: {
									"@acl"  : [$ACL.USER_TYPE_ADMIN],
									"@doc"  : "Create a new report template with header settings, sections, and fields.",
									"#token": "s",
									"name"                    : "s***Template name (max 80 chars)",
									"category"                : "s***Report category: " + $DataItems.getListForApiDoc("report_category"),
									"community_ids"           : "n***Array of community IDs, or empty array for global",
									"title_format"            : "s***Report title pattern. Supports placeholders: {date}, {community}, {officer}, {template_name}, {incident_type}",
									"review_before_client"    : "o:b:false***Route completed reports to manager review before client delivery",
									"allow_officer_editing"   : "o:b:false***Allow officers to edit submitted reports before manager review",
									"sections"                : "a***Array of section objects: [{title, is_enabled, is_required, client_visible, fields: [{field_key, label, description, field_type, config, is_system_field, is_required}]}]",
								},
	"update_template"			: {
									"@acl"  : [$ACL.USER_TYPE_ADMIN],
									"@doc"  : "Update template header settings and/or sections. Only draft and active templates can be updated.",
									"#token": "s",
									"template_id"             : "i***Report Template ID",
									"name"                    : "o:s:/null/***Template name (max 80 chars)",
									"category"                : "o:s:/null/***Report category: " + $DataItems.getListForApiDoc("report_category"),
									"community_ids"           : "o:n:/null/***Array of community IDs, or empty array for global",
									"title_format"            : "o:s:/null/***Report title pattern with placeholders",
									"review_before_client"    : "o:b:/null/***Route completed reports to manager review",
									"allow_officer_editing"   : "o:b:/null/***Allow officers to edit submitted reports",
									"sections"                : "o:a:/null/***Full replacement array of sections (same structure as create)",
								},
	"duplicate_template"		: {
									"@acl"  : [$ACL.USER_TYPE_ADMIN],
									"@doc"  : "Duplicate an existing template. The new template is created in draft status with a copy of all sections and fields.",
									"#token": "s",
									"template_id"    : "i***Source Report Template ID to duplicate",
									"name"           : "o:s:***New template name (defaults to 'Copy of <original>')",
								},
	"archive_template"			: {
									"@acl"  : [$ACL.USER_TYPE_ADMIN],
									"@doc"  : "Archive a template. Archived templates are not available for new reports. Existing reports are unaffected.",
									"#token": "s",
									"template_id"    : "i***Report Template ID",
								},
	"activate_template"			: {
									"@acl"  : [$ACL.USER_TYPE_ADMIN],
									"@doc"  : "Activate a draft or archived template, making it visible to officers for report creation.",
									"#token": "s",
									"template_id"    : "i***Report Template ID",
								},
	"delete_template"			: {
									"@acl"  : [$ACL.USER_TYPE_ADMIN],
									"@doc"  : "Soft-delete a template. Only draft templates (or templates with no linked reports) can be deleted. Use archive_template for active templates.",
									"#token": "s",
									"template_id"    : "i***Report Template ID",
								},
	"get_template_style"		: {
									"@acl"  : [$ACL.USER_TYPE_ADMIN],
									"@doc"  : "Get template formatting/style settings (logo, colors, fonts, layout, etc.).",
									"#token": "s",
									"template_id"    : "i***Report Template ID",
								},
	"update_template_style"		: {
									"@acl"  : [$ACL.USER_TYPE_ADMIN],
									"@doc"  : "Update template formatting/style settings for PDF/client-facing report generation.",
									"#token": "s",
									"template_id"             : "i***Report Template ID",
									"company_logo"            : "o:s:/null/***Logo image data (base64) or empty string to remove",
									"accent_color"            : "o:s:/null/***Hex colour for section headings and dividers (e.g. #1A2B3C)",
									"header_layout"           : "o:s:/null/***Header layout: " + $DataItems.getListForApiDoc("report_header_layout"),
									"font"                    : "o:s:/null/***Font family: " + $DataItems.getListForApiDoc("report_font"),
									"page_numbering"          : "o:b:/null/***Show page numbers in footer",
									"confidentiality_footer"  : "o:s:/null/***Footer text for each page",
									"date_format"             : "o:s:/null/***Date format: " + $DataItems.getListForApiDoc("report_date_format"),
									"section_breaks"          : "o:s:/null/***Section breaks: " + $DataItems.getListForApiDoc("report_section_breaks"),
									"include_cover_page"      : "o:b:/null/***Generate a dedicated cover page",
								},
};
